server:
  port: 3000
  error:
    include-message: always

springdoc.swagger-ui.path: /swagger.html
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybank
    username: postgres
    password: postgres
    initialize: tr ue
    platform: postgresql
  jackson:
    property-naming-strategy: SNAKE_CASE


